import yaml from "js-yaml";
import type { CatalogDocument } from "./types";

const HEADER = `# Open Insurance Engine - business catalog
#
# Generated by Rules Studio. Domain classes compile these declarations;
# they do not hardcode the business rules.
#
# Underwriting facts: driverAge, lineOfBusiness, coverageCount, hasVehicle
# FNOL facts:          policyInForce, totalReserves, coverageLimit, tier
# Claim checks:        description, lossDate
# Rating sources:      profile.age | profile.yearsLicensed | profile.priorClaimsLast3Years
#                      profile.creditBand | profile.regionCode
#                      vehicle.annualMileage | vehicle.ageYears
#
# when.op: lt | lte | gt | gte | eq | neq | in | isTrue | isFalse
# when.value: scalar or list; when.otherField compares two facts
# Money facts (totalReserves, coverageLimit) are major units
`;

function cleanWhen(when: CatalogDocument["underwriting"]["rules"][0]["when"]) {
  const next: Record<string, unknown> = { field: when.field, op: when.op };
  if (when.otherField) next.otherField = when.otherField;
  else if (when.op !== "isTrue" && when.op !== "isFalse" && when.value !== undefined && when.value !== "") {
    next.value = coerceValue(when.op, when.value);
  }
  return next;
}

function coerceValue(op: string, raw: unknown): unknown {
  if (op === "in") {
    if (Array.isArray(raw)) return raw;
    if (typeof raw === "string")
      return raw
        .split(",")
        .map((s) => s.trim())
        .filter(Boolean);
  }
  if (typeof raw === "string") {
    const t = raw.trim();
    if (t === "true") return true;
    if (t === "false") return false;
    if (t !== "" && !Number.isNaN(Number(t))) return Number(t);
    return raw;
  }
  return raw;
}

function cleanRule(rule: CatalogDocument["underwriting"]["rules"][0]) {
  const next: Record<string, unknown> = {
    id: rule.id,
    name: rule.name,
    priority: Number(rule.priority),
    action: rule.action,
    when: cleanWhen(rule.when),
    reason: rule.reason
  };
  if (rule.enabled === false) next.enabled = false;
  return next;
}

function cleanBand(band: CatalogDocument["rating"]["tables"][0]["bands"][0]) {
  const next: Record<string, unknown> = { label: band.label, factor: Number(band.factor) };
  if (band.code) next.code = band.code;
  if (band.min !== undefined && band.min !== null && String(band.min) !== "") next.min = Number(band.min);
  if (band.max !== undefined && band.max !== null && String(band.max) !== "") next.max = Number(band.max);
  return next;
}

function cleanFactor(factor: CatalogDocument["rating"]["plans"][0]["factors"][0]) {
  const next: Record<string, unknown> = {
    code: factor.code,
    name: factor.name,
    weight: Number(factor.weight),
    table: factor.table,
    source: factor.source
  };
  if (factor.fallback) next.fallback = factor.fallback;
  if (factor.default !== undefined && factor.default !== null && String(factor.default) !== "") {
    next.default = Number(factor.default);
  }
  return next;
}

export function dumpCatalog(doc: CatalogDocument): string {
  const body = {
    underwriting: {
      id: doc.underwriting.id,
      name: doc.underwriting.name,
      rules: doc.underwriting.rules.map(cleanRule)
    },
    fnol: {
      id: doc.fnol.id,
      name: doc.fnol.name,
      rules: doc.fnol.rules.map(cleanRule)
    },
    claimValidation: doc.claimValidation,
    rating: {
      defaultBaseRateMajor: Number(doc.rating.defaultBaseRateMajor),
      currency: doc.rating.currency,
      tables: doc.rating.tables.map((t) => ({
        id: t.id,
        name: t.name,
        kind: t.kind,
        bands: t.bands.map(cleanBand)
      })),
      plans: doc.rating.plans.map((p) => ({
        id: p.id,
        name: p.name,
        mode: p.mode,
        factors: p.factors.map(cleanFactor)
      }))
    }
  };
  return `${HEADER}\n${yaml.dump(body, { lineWidth: 120, noRefs: true, quotingType: '"' })}`;
}

export function parseCatalog(text: string): CatalogDocument {
  const loaded = yaml.load(text) as CatalogDocument;
  if (!loaded?.underwriting || !loaded?.fnol || !loaded?.rating) {
    throw new Error("YAML is missing underwriting, fnol or rating");
  }
  return {
    underwriting: loaded.underwriting,
    fnol: loaded.fnol,
    claimValidation: loaded.claimValidation ?? [],
    rating: loaded.rating
  };
}
