name: Unit tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup SBT
      uses: sbt/setup-sbt@v1

    - name: Run unit tests
      run: sbt test

    - name: Run demo scenario
      run: sbt "app/run --demo"
